import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

// generated by shadcn
export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

// created by chatgpt
export function isBase64Image(imageData: string) {
  const base64Regex = /^data:image\/(png|jpe?g|gif|webp);base64,/;
  return base64Regex.test(imageData);
}


export function calculateWidth(windowWidth: number) {
    if (windowWidth <= 390) {
      return [300, 180];
    }

    if (windowWidth <= 680 && windowWidth > 450) {
      return [390, 230];
    }

    if (windowWidth <= 450) {
      return [350, 200];
    }
    
    return [640, 360];
}