import React from "react";
import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

// clerk
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Auth",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}>
      <html lang="en">
        <body
          className={`${inter.className} bg-[#00060f] w-full min-h-screen flex justify-center items-center`}>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
